# Generated by Django 6.0.3 on 2026-08-30 19:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if still occupying', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Occupancy',
                'verbose_name_plural': 'Occupancies',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('due_date', models.DateField(help_text='Date by which payment should be made')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sanitation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('occupancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='revenuecollection.occupancy')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-billing_period_start'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(default=uuid.uuid4, help_text='Unique reference generated for MTN MoMo request', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(help_text="Payer's MTN Mobile Money number (may differ from vendor's own number)", max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+256XXXXXXXXX' (Uganda)", regex='^\\+?256\\d{9}$')])),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=10)),
                ('momo_transaction_id', models.CharField(blank=True, help_text='Transaction ID returned by MTN after success', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='revenuecollection.invoice')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique identifier, e.g., 'ST-001' or 'LK-102'", max_length=20, unique=True)),
                ('property_type', models.CharField(choices=[('stall', 'Stall'), ('lockup', 'Lockup Shop')], max_length=10)),
                ('location', models.CharField(blank=True, help_text='e.g., Block A, Row 2', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rent_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sanitation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('security_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['property_type'], name='revenuecoll_propert_ba3716_idx'), models.Index(fields=['is_active'], name='revenuecoll_is_acti_be1edf_idx')],
            },
        ),
        migrations.AddField(
            model_name='occupancy',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='revenuecollection.property'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(help_text='MTN Mobile Money number (Uganda format: +256XXXXXXXXX)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+256XXXXXXXXX' (Uganda)", regex='^\\+?256\\d{9}$')])),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vendor_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['is_active'], name='revenuecoll_is_acti_563518_idx')],
            },
        ),
        migrations.AddField(
            model_name='occupancy',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='revenuecollection.vendor'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_via', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='revenuecollection.vendor')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='revenuecoll_status_7aa564_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='revenuecoll_due_dat_bdc422_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='revenuecoll_status_6e8d99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='revenuecoll_status_cb8e73_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['is_active'], name='revenuecoll_is_acti_3e7fa6_idx'),
        ),
        migrations.AddConstraint(
            model_name='occupancy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('property',), name='unique_active_occupancy_per_property'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['vendor', 'sent_at'], name='revenuecoll_vendor__c4eaa4_idx'),
        ),
    ]
