# Generated by Django 6.0.3 on 2026-08-30 19:28

import cloudinary.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenuecollection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPNLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.TextField()),
                ('order_tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IPN Log',
                'verbose_name_plural': 'IPN Logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='momo_transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='pesapal_order_tracking_id',
            field=models.CharField(blank=True, help_text='Pesapal order tracking ID returned after submission', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(help_text="Payer's phone number (may differ from vendor)", max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+256XXXXXXXXX' (Uganda)", regex='^\\+?256\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_ref',
            field=models.CharField(default=uuid.uuid4, help_text='Our unique merchant reference (sent to Pesapal)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(help_text='Phone number (Uganda format: +256XXXXXXXXX)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+256XXXXXXXXX' (Uganda)", regex='^\\+?256\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
