# Generated by Django 6.0.3 on 2026-08-30 23:12

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenuecollection', '0002_ipnlog_remove_payment_momo_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-billing_period_start']},
        ),
        migrations.AlterModelOptions(
            name='ipnlog',
            options={'ordering': ['-received_at']},
        ),
        migrations.AlterModelOptions(
            name='occupancy',
            options={'verbose_name_plural': 'Occupancies'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pesapal_order_tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+256XXXXXXXXX' (Uganda)", regex='^\\+?256\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_ref',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+256XXXXXXXXX' (Uganda)", regex='^\\+?256\\d{9}$')]),
        ),
    ]
