# Generated by Django 6.0.3 on 2026-08-31 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenuecollection', '0003_alter_invoice_options_alter_ipnlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_ref',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
